language: node_js
node_js:
  - 'lts/*'
  - 'node'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script:
  - greenkeeper-lockfile-upload
